server:
  servlet:
    contextPath: /test-api
  port: ${PORT:3000}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    name: test-railway-api
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
      