server:
  servlet:
    contextPath: /test-api
  port: ${PORT:3000}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:containers-us-west-138.railway.app}:${DB_PORT:6422}/${DB_NAME:railway}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:DQJbG2zTagEnb9KoDkQV}
    name: test-railway-api

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
      
      